server:
  port: 1000
#  tomcat.accept-count: 100 # Maximum queue length for incoming connection requests when all possible request processing threads are in use.
#  tomcat.additional-tld-skip-patterns: # Comma-separated list of additional patterns that match jars to ignore for TLD scanning.
#  tomcat.background-processor-delay: 10s # Delay between the invocation of backgroundProcess methods. If a duration suffix is not specified, seconds will be used.
#  tomcat.basedir: # Tomcat base directory. If not specified, a temporary directory is used.
#  tomcat.max-connections: 10000 # Maximum number of connections that the server accepts and processes at any given time.
#  tomcat.max-http-header-size: 0 # Maximum size in bytes of the HTTP message header.
#  tomcat.max-http-post-size: 2097152 # Maximum size in bytes of the HTTP post content.
#  tomcat.max-threads: 200 # Maximum amount of worker threads.
#  tomcat.min-spare-threads: 10 # Minimum amount of worker threads.
#  tomcat.port-header: X-Forwarded-Port # Name of the HTTP header used to override the original port value.
##  tomcat.protocol-header: # Header that holds the incoming protocol, usually named "X-Forwarded-Proto".
##  tomcat.protocol-header-https-value: https # Value of the protocol header indicating whether the incoming request uses SSL.
#  tomcat.redirect-context-root: true # Whether requests to the context root should be redirected by appending a / to the path.
##  tomcat.remote-ip-header: # Name of the HTTP header from which the remote IP is extracted. For instance, `X-FORWARDED-FOR`.
##  tomcat.resource.cache-ttl: # Time-to-live of the static resource cache.
#  tomcat.uri-encoding: UTF-8 # Character encoding to use to decode the URI.
##  tomcat.use-relative-redirects: # Whether HTTP 1.1 and later location headers generated by a call to sendRedirect will use relative or absolute redirects.

  tomcat:
    threads:
      max: 200 # 생성할 수 있는 thread의 총 개수
      min-spare: 10 # 항상 활성화 되어있는(idle) thread의 개수
    max-connections: 8192 # 수립가능한 connection의 총 개수
    accept-count: 100 # 작업큐의 사이즈
    connection-timeout: 20000 # timeout 판단 기준 시간, 20초

spring:
  application:
    name: spring-transaction
  profiles:
    active: h2, jpa
