spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-mvc
  profiles:
    active: jpa,test1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul

datasource:
  db1:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/default
    username: root
    password: 1234

  db2:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234


---
