INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
INSERT INTO current_dt(JAVA_DT, SQL_DT)
values (SYSTIMESTAMP, SYSTIMESTAMP);
