spring:
  sql:
    init:
      mode: always
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
    h2:
      console:
        enabled: true
  datasource:
#    initialization-mode: always
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9095/mem:testdb;DB_CLOSE_DELAY=-1
      username: sa
      password:
  jpa:
    #
    defer-datasource-initialization: true

