version: '3'
services:
  db1:
    image: arm64v8/mariadb
    restart: always
    ports:
      - "53306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: 1234
    container_name: "mvc_db1"
    volumes:
      - ./db1/maria:/var/lib/mysqlysql
      # init.sql
      - ./db1/sql:/docker-entrypoint-initdb.d
  db2:
    image: arm64v8/postgres
    restart: always
    ports:
      - "55432:5432"
    container_name: "mvc_db2"
    environment:
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db2/mount:/var/lib/postgresql/data